collections:
    - name: ansible.netcommon
    - name: ansible.posix
    - name: ansible.utils
    - name: ansible.windows
    - name: awx.awx
    - name: cisco.aci
    - name: cisco.asa
    - name: cisco.dnac
    - name: cisco.intersight
    - name: cisco.ios
    - name: cisco.iosxr
    - name: cisco.ise
    - name: cisco.meraki
    - name: cisco.mso
    - name: cisco.nso
    - name: cisco.nxos
    - name: cisco.ucs
    - name: community.aws
    - name: community.azure
    - name: community.ciscosmb
    - name: community.crypto
    - name: community.digitalocean
    - name: community.dns
    - name: community.docker
    - name: community.fortios
    - name: community.general
    - name: community.google
    - name: community.grafana
    - name: community.hashi_vault
    - name: community.hrobot
    - name: community.libvirt
    - name: community.mongodb
    - name: community.mysql
    - name: community.network
    - name: community.okd
    - name: community.postgresql
    - name: community.proxysql
    - name: community.rabbitmq
    - name: community.routeros
    - name: community.sap
    - name: community.sap_libs
    - name: community.skydive
    - name: community.sops
    - name: community.windows
    - name: community.zabbix
    - name: dellemc.enterprise_sonic
    - name: dellemc.openmanage
    - name: dellemc.os10
    - name: dellemc.os6
    - name: dellemc.os9
    - name: dellemc.powerflex
    - name: dellemc.unity
    - name: f5networks.f5_modules
    - name: kubernetes.core