name: Build AWX EE image

on:
  push:
    branches: ['master']
    tags:
      - "v*"
  
jobs:
  build-ee-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/syt-rocstar/rcs-awx-ee
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install ansible-builder
        run: pip3 install ansible-builder

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build EE image
        run: |
          ansible-builder build \
          --tag ghcr.io/syt-rocstar/awx-ee:latest \
          --tag ${{ steps.meta.outputs.tags }} \
          --container-runtime docker \
          -f execution-environment.yml

      - name: Push EE image
        if: github.ref_type == 'tag'
        run: |
          docker push ghcr.io/syt-rocstar/rcs-awx-ee -a
